version: "3"
services:
  practice:
    image: php:apache
    ports:
      - 8080:80
    volumes: 
        - ./practice:/var/www/html
  secret:
    image: php:apache
    ports:
      - 8081:80
    volumes: 
        - ./secret:/var/www/html
  attacker:
    image: php:apache
    ports:
      - 8082:80
    volumes: 
        - ./attacker:/var/www/html
  trusted:
    image: php:apache
    ports:
      - 8083:80
    volumes: 
        - ./trusted:/var/www/html